config_version = "2.0"
configuration = []

[info]
name = "Bootloader App"
description = "This App connects to assigned devices and if they are a PoE-based device, flashes newest firmware."

[runtime]
application = "app.py#Application"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2:2023.275.1315-rvc2-regular"
