config_version = "2.0"
configuration = []

[info]
name = "Emotion Recognition App"
description = "This app detects faces and emotions."

[runtime]
application = "app.py#Application"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2:2023.275.1315-rvc2-regular"
