config_version = "2.0"
configuration = []

[info]
name = "Object Detection Demo app"
description = "This app live-streams detections from a YoloV6 network."

[runtime]
application = "app.py#ObjectDetection"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2:2023.107.1353-experimental-custom-dev"
