config_version = "2.0"

[info]
name = "QR Reader"
description = "This is a generated description. Replace it with your own."

[runtime]
application = "app.py#Application"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/qr_detector:v1.0.0"

#[runtime.runs_on]
#type = "custom"
#dockerfile = "Dockerfile"

[[configuration]]
visual = "section"
title = "Camera config"

[[configuration]]
field = "choice"
key = "resolution"
label = "Resolution"
style = "radio"
allow_multiple = false
options = [
  { key = "1080p", label = "1080p" },
  { key = "4k", label = "4k", default=true },
  { key = "5312x6000", label = "5312x6000" }
]

[[configuration]]
key = "exposure_limit"
label = "Automatic Exposure Limit (microseconds)"
field = "num_range"
step = 125
min = 100
max = 30000
initial_value = 20000

[[configuration]]
key = "enable_manual_exposure"
label = "Enable Manual Exposure and ISO"
field = "boolean"
initial_value = false

[[configuration]]
key = "manual_exposure"
label = "Manual Exposure (microseconds)"
field = "num_range"
step = 125
min = 100
max = 30000
initial_value = 30000

[[configuration]]
key = "manual_iso"
label = "Manual ISO"
field = "num_range"
step = 25
min = 100
max = 1600
initial_value = 200

[[configuration]]
key = "manual_focus"
label = "Manual Focus (0 = disabled)"
field = "num_range"
step = 1
min = 0
max = 255
initial_value = 0
